### ISSUE TITLE
Multimedia codecs install failed 

### ISSUE THREAD

**Issue by gitgt** [folkswithhats/fedy#259]
[F22 x64] Multimedia codecs install failed with fedy-3.2.1.

**Comment by gitgt** [comment]
Also with version from Git as of today (I don't know how to say which version).

**Comment by satya164** [comment]
It should be fixed now. Please uninstall `ozon-repos` and `fedy` packages and use the installation script from here - folkswithhats.org

**Comment by japellerano** [comment]
Still no luck even with the new packages and installation script.

**Comment by japellerano** [comment]
Fixed mine:

sudo dnf remove fedy
sudo rpm -qa | grep rpmfusion
sudo rpm -r rpmfusion-nonfree-release-22-1.noarch
sudo rpm -r rpmfusion-free-release-22-1.noarch
sudo dnf clean all

Go to http://folkswithhats.org and update the installer.

**Comment by gitgt** [comment]
Works with 4.0.6.
